table month_range
	lineageTag: e0388fc4-2e06-4129-9040-8b65fb94aed7

	column range
		dataType: string
		lineageTag: 77a5c9c4-cf4a-4f7e-b6ed-ef49c6e27892
		summarizeBy: none
		sourceColumn: range

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: dateTime
		formatString: Long Date
		lineageTag: 09c41743-a0f0-4480-b926-e9f0c7a13819
		summarizeBy: none
		sourceColumn: Month

		variation Variation
			isDefault
			relationship: ed69250e-8f78-4e36-9042-0d2a6b1543a0
			defaultHierarchy: LocalDateTable_65528c43-5ba7-467b-aba5-a503ef1eb1e0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MonthYear
		dataType: string
		lineageTag: d973d07e-3e2f-4f25-bcea-09ea0fbce922
		summarizeBy: none
		sourceColumn: MonthYear
		sortByColumn: Month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition month_range = m
		mode: import
		source =
				let
				    Source = PowerBI.Dataflows(null),
				    Workspacedata = Source{[workspaceId=Workspace]}[Data],
				    Dataflowdata = Workspacedata{[dataflowId=Dataflow]}[Data],
				    interim_checkpoint1 = Dataflowdata{[entity="interim_checkpoint"]}[Data],
				    SelectedColumns = Table.SelectColumns(interim_checkpoint1,{"week_start_date", "week_end_date"}),
				    Distinctweeks = Table.Distinct(SelectedColumns),
				    AddDates = Table.AddColumn(Distinctweeks, "Date", each List.Transform({Number.From([week_start_date])..Number.From([week_end_date])}, Date.From)),
				    ExpandDates = Table.ExpandListColumn(AddDates, "Date"),
				    DateFormat = Table.TransformColumnTypes(ExpandDates,{{"Date", type date}}),
				    AddMonth = Table.AddColumn(DateFormat, "Month", each Date.StartOfMonth ([Date])),
				    MonthFormat = Table.TransformColumnTypes(AddMonth,{{"Month", type date}}),
				    DeleteDates = Table.RemoveColumns(MonthFormat,{"Date"}),
				    DistinctTable = Table.Distinct(DeleteDates),
				    FilterMonths = Table.SelectRows(DistinctTable, each [Month] <= Date.StartOfMonth(Date.From(DateTime.LocalNow()))),
				    AddRange = Table.CombineColumns(Table.TransformColumnTypes(FilterMonths, {{"week_start_date", type text}, {"week_end_date", type text}}, "en-US"),{"week_start_date", "week_end_date"},Combiner.CombineTextByDelimiter("-", QuoteStyle.None),"range"),
				    AddMonthYear = Table.AddColumn(AddRange, "MonthYear", each Text.Combine({Date.MonthName([Month]), Text.From(Date.Year([Month]))}, "-"))
				in
				    AddMonthYear

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

